# Generated by Django 3.2.8 on 2021-11-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormDashApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('food_pic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
