# Generated by Django 3.2.8 on 2021-12-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormDashApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='food_type',
            field=models.TextField(choices=[('A', 'Appetizer'), ('E', 'Entree'), ('D', 'Dessert'), ('S', 'Side'), ('R', 'Drink')], max_length=1),
        ),
    ]
