# Generated by Django 4.1.dev20211011185258 on 2021-12-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormDashApp', '0002_alter_menuitem_food_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='000@000.com', max_length=30),
        ),
    ]
