# Generated by Django 3.2.8 on 2021-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormDashApp', '0003_menuitem_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='Other'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
