# Generated by Django 3.2.8 on 2021-11-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormDashApp', '0004_auto_20211130_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='Other', max_length=144),
        ),
    ]
